# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := d8_js2c
### Rules for action "d8_js2c":
quiet_cmd_d8_js2c_d8_js2c = ACTION d8_js2c_d8_js2c $@
cmd_d8_js2c_d8_js2c = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd src; mkdir -p $(obj)/gen; python ../tools/js2c.py "$(obj)/gen/d8-js.cc" D8 off d8.js macros.py

$(obj)/gen/d8-js.cc: obj := $(abs_obj)

$(obj)/gen/d8-js.cc: export TARGET_BUILD_DIR := ../$(abs_builddir)
$(obj)/gen/d8-js.cc: export FULL_PRODUCT_NAME := $(obj).target/src/d8_js2c.stamp
$(obj)/gen/d8-js.cc: export SRCROOT := .
$(obj)/gen/d8-js.cc: export BUILT_PRODUCTS_DIR := ../$(abs_builddir)
$(obj)/gen/d8-js.cc: export TEMP_DIR := $(TMPDIR)
$(obj)/gen/d8-js.cc: export CONFIGURATION := $(BUILDTYPE)
$(obj)/gen/d8-js.cc: export PRODUCT_NAME := $(obj).target/src/d8_js2c.stamp
$(obj)/gen/d8-js.cc: builddir := $(abs_builddir)

$(obj)/gen/d8-js.cc: TOOLSET := $(TOOLSET)
$(obj)/gen/d8-js.cc: tools/js2c.py src/d8.js src/macros.py FORCE_DO_CMD
	$(call do_cmd,d8_js2c_d8_js2c)

all_deps += $(obj)/gen/d8-js.cc
action_d8_js2c_d8_js2c_outputs := $(obj)/gen/d8-js.cc


### Rules for final target.
# Build our special outputs first.
$(obj).target/src/d8_js2c.stamp: | $(action_d8_js2c_d8_js2c_outputs)

# Preserve order dependency of special output on deps.
$(action_d8_js2c_d8_js2c_outputs): | 

$(obj).target/src/d8_js2c.stamp: TOOLSET := $(TOOLSET)
$(obj).target/src/d8_js2c.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/src/d8_js2c.stamp
# Add target alias
.PHONY: d8_js2c
d8_js2c: $(obj).target/src/d8_js2c.stamp

# Add target alias to "all" target.
.PHONY: all
all: d8_js2c

